#Author: Felix Kleine Bösing
# Compose for checkers app (python backend, react frontend)

version: '2'

services:

  pybackend:
    build: ./checkers/
    image: checkers_python_backend
    restart: always
    container_name: checkers_python
    volumes:
      - ./checkers/src:/checkers/src
    networks:
      - pydb
      - pyjs
    environment:
      - test=123
    ports:
      - 127.0.0.1:5001:5001
    command:
      - /checkers/src/API.py

  pyredis:
    image: redis:5
    container_name: checkers_redis
    ports:
      - 127.0.0.1:6379:6379
    networks:
      - pydb

  pypostgres:
    image: postgres:11
    container_name: checkers_postgres
    ports:
      127.0.0.1:5432:5432
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: postgres
      POSTGRES_DB: game-results
    volumes:
      - ./mountingData/transactionDB:/var/lib/postgresql/data
    networks:
      - pydb


networks:
  pyjs:
  pydb: