#Author: Felix Kleine Bösing
# Compose for checkers app (python backend, react frontend)

version: '2'

services:

  pybackend:
    build: ./python_backend/
    image: checkers_python_backend
    restart: always
    container_name: checkers_python
    volumes:
      - ./python_backend/src:/python_backend/src
    networks:
      - pyjs
    environment:
      - test=123
    ports:
      - 127.0.0.1:5001:5001
    command:
      - import time; time.sleep(6000)
      #- /python_backend/src/API.py

networks:
  pyjs: